import { Poppins } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "600"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={poppins.className + " flex flex-col place-items-center"}>
          <main className="max-w-[1000px] m-5">
            {children}
          </main>
        </body>
      </UserProvider>
    </html>
  );
}
